version: '3.9'

services:
  example_db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    container_name: 'example_db'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/01-init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=3x4mpl3
      - POSTGRES_DB=example
    networks:
      - example-network

  example_api:
    container_name: example_api
    image: example_api:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: yarn start
    depends_on:
      - example_db
    env_file: ./.env
    ports:
      - 3000:3000
    networks:
      - example-network

networks:
  example-network:

volumes: 
  pg-data: